/**
 * scrubBrandText — last line of defence for any outward-facing text.
 *
 * HARD RULES enforced here (not in prompts):
 *   - No em-dashes (—) or en-dashes (–) in outward-facing copy
 *   - Artist name is always "NIGHT manoeuvres" (NIGHT caps, manoeuvres lowercase)
 *   - Never leak AI / automation / bot / "as an AI" phrasing
 *
 * Every Claude-powered route that emits outward-facing text
 * (emails, invoices, DMs, captions, replies, ad copy) must pass its
 * generated string through scrubBrandText() before returning to the client.
 *
 * Prompt obedience is not a security boundary. This function is.
 */

const AI_TELL_PATTERNS: RegExp[] = [
  /\bas an ai\b/gi,
  /\bas a language model\b/gi,
  /\bi am an ai\b/gi,
  /\bi'?m an ai\b/gi,
  /\bgenerated by ai\b/gi,
  /\b(this|the) (email|message|caption|invoice|reply) was (written|generated|created) (by|using|with) ai\b/gi,
  /\bpowered by (claude|chatgpt|gpt|openai|anthropic)\b/gi,
]

export function scrubBrandText(input: string | null | undefined): string {
  if (!input) return ''
  let s = String(input)

  // Dash replacements — em and en dashes read as AI
  s = s.replace(/—/g, ',').replace(/–/g, ',')

  // NIGHT manoeuvres casing — collapse every variant to the one canonical form
  s = s
    .replace(/NIGHT MANOEUVRES/g, 'NIGHT manoeuvres')
    .replace(/Night Manoeuvres/g, 'NIGHT manoeuvres')
    .replace(/night manoeuvres/g, 'NIGHT manoeuvres')
    .replace(/Night manoeuvres/g, 'NIGHT manoeuvres')
    .replace(/NIGHT Manoeuvres/g, 'NIGHT manoeuvres')
    // US spelling variant safeguard
    .replace(/NIGHT MANEUVERS/g, 'NIGHT manoeuvres')
    .replace(/Night Maneuvers/g, 'NIGHT manoeuvres')
    .replace(/night maneuvers/g, 'NIGHT manoeuvres')

  // AI tells — strip to empty; caller gets cleaner copy
  for (const re of AI_TELL_PATTERNS) s = s.replace(re, '')

  // Collapse double-spaces introduced by removals
  s = s.replace(/[ \t]{2,}/g, ' ').replace(/ ,/g, ',')

  return s
}

/** Convenience for objects that hold multiple text fields. */
export function scrubBrandFields<T extends Record<string, any>>(obj: T, keys: (keyof T)[]): T {
  const out: any = { ...obj }
  for (const k of keys) {
    if (typeof out[k] === 'string') out[k] = scrubBrandText(out[k])
  }
  return out
}
