-- Crew briefing drafts — generated by night-before cron, approved by artist before sending
CREATE TABLE IF NOT EXISTS crew_briefing_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  gig_id UUID NOT NULL,
  recipient_name TEXT,
  recipient_email TEXT NOT NULL,
  recipient_role TEXT,
  subject TEXT NOT NULL,
  body_html TEXT NOT NULL,
  body_text TEXT NOT NULL,
  upload_url TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'expired')),
  sent_at TIMESTAMPTZ,
  approved_via TEXT CHECK (approved_via IN ('app', 'sms'))
);

-- Index for quick lookup by gig
CREATE INDEX IF NOT EXISTS idx_crew_briefing_gig ON crew_briefing_drafts(gig_id);
CREATE INDEX IF NOT EXISTS idx_crew_briefing_status ON crew_briefing_drafts(status);
